[[redirects]]
from = "/"
to = "/es"
status = 301
force = true
conditions = {Country = ["AR", "BO", "CL", "CO", "CR", "CU", "DO", "EC", "SV", "GQ", "GT", "HN", "MX", "NI", "PA", "PY", "PE", "PR", "ES", "UY", "VE"]}

[[redirects]]
from = "/"
to = "/de"
status = 301
force = true
conditions = {Country = ["AT", "BE", "CH", "DE", "LI", "LU"]}

[[redirects]]
from = "/"
to = "/en"
status = 301
force = true