[[redirects]]
  from = "/test6"
  to = "/es"
  status = 301
  force = false
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/test6"
  to = "/de"
  status = 301
  force = false
  conditions = {Language = ["de"]}