export const dataLanguageTexts = {
  es: {
    inputTitle: "Buscador de Especialistas en Podología",
    inputPlaceholder: "Buscá especialistas por palabra clave",
    filterBy: "Filtrar por",
    resetFilters: "Reiniciar el fitro",
    ranking: "Ranking",
    profession: "Ocupación",
    services: "Servicios",
    noResults: "Sin resultados",
    noResultsExplain: "Intente cambiar los filtros o buscar algo diferente",
    allResults: "Todos los resultados",
    allCountries: "Todos los paises",
    allIn: "Todos en",
    noServices: "¿No está en la lista?",
    moreInfo: "Más información"
  },
  de: {
    inputTitle: "Suche nach Podologie-Spezialisten",
    inputPlaceholder: "Spezialisten nach Stichworten suchen",
    filterBy: "Filtern nach",
    resetFilters: "Filter zurücksetzen",
    ranking: "Ranking",
    profession: "Beruf",
    services: "Dienstleistungen",
    noResults: "Keine Ergebnisse",
    noResultsExplain: "Versuchen Sie, die Filter zu ändern oder nach etwas anderem zu suchen",
    allResults: "Alle Ergebnisse",
    allCountries: "Alle Länder",
    allIn: "Alles in",
    noServices: "Sie sind nicht gelistet?",
    moreInfo: "Mehr erfahren"
  },
  en: {
    inputTitle: "Search Podiatry Specialists",
    inputPlaceholder: "Search specialists by keyword",
    filterBy: "Flter by",
    resetFilters: "Reset filters",
    ranking: "Ranking",
    profession: "Profession",
    services: "Services",
    noResults: "No results",
    noResultsExplain: "Try to change the filters or search for something else",
    allResults: "All the results",
    allCountries: "All countries",
    allIn: "All in",
    noServices: "Not listed?",
    moreInfo: "Learn more"
  },
};
